# Generated by Django 4.0.6 on 2022-07-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.CharField(choices=[('G', 'Great'), ('O', 'Okay'), ('T', 'Terrible')], default='G', max_length=1),
        ),
    ]
