# Generated by Django 4.0.6 on 2022-07-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_store_alter_feedback_date_alter_feedback_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stores',
            field=models.ManyToManyField(to='main_app.store'),
        ),
    ]
