# Generated by Django 4.0.6 on 2022-07-25 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_book_stores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(verbose_name='feedback date'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='score',
            field=models.CharField(choices=[('G', 'Great'), ('O', 'Okay'), ('T', 'Terrible')], default='G', max_length=1),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.book')),
            ],
        ),
    ]
